#include <bravo/protocol/get_config.hpp>
#include <bravo/protocol/config.hpp>
#include <bravo/protocol/asset.hpp>
#include <bravo/protocol/types.hpp>
#include <bravo/protocol/version.hpp>

namespace bravo { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
#else
   result[ "IS_TEST_NET" ] = false;
#endif
   result["BRAVO_INIT_MINED_COIN_PER_BLOCK"] = BRAVO_INIT_MINED_COIN_PER_BLOCK;
   result["BRAVO_MINED_COIN_HALVED_TIME"] = BRAVO_MINED_COIN_HALVED_TIME;
   result["BRAVO_MINED_COIN_HALVED_BLOCK"] = BRAVO_MINED_COIN_HALVED_BLOCK;
   result["BRAVO_CONTENT_REWARD_PERCENT"] = BRAVO_CONTENT_REWARD_PERCENT;
   result["BRAVO_CONTENT_REWARD_PERCENT_HF23"] = BRAVO_CONTENT_REWARD_PERCENT_HF23;
   result["BRAVO_CUSTOME_OP_FEE"] = BRAVO_CUSTOME_OP_FEE;
   result["BRAVO_MIN_PAYOUT"] = BRAVO_MIN_PAYOUT;
   result["BRAVO_100_PERCENT"] = BRAVO_100_PERCENT;
   result["BRAVO_1_PERCENT"] = BRAVO_1_PERCENT;
   result["BRAVO_1_TENTH_PERCENT"] = BRAVO_1_TENTH_PERCENT;
   result["BRAVO_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = BRAVO_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["BRAVO_ACTIVE_CHALLENGE_COOLDOWN"] = BRAVO_ACTIVE_CHALLENGE_COOLDOWN;
   result["BRAVO_ACTIVE_CHALLENGE_FEE"] = BRAVO_ACTIVE_CHALLENGE_FEE;
   result["BRAVO_ADDRESS_PREFIX"] = BRAVO_ADDRESS_PREFIX;
   result["BRAVO_APR_PERCENT_MULTIPLY_PER_BLOCK"] = BRAVO_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["BRAVO_APR_PERCENT_MULTIPLY_PER_HOUR"] = BRAVO_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["BRAVO_APR_PERCENT_MULTIPLY_PER_ROUND"] = BRAVO_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["BRAVO_APR_PERCENT_SHIFT_PER_BLOCK"] = BRAVO_APR_PERCENT_SHIFT_PER_BLOCK;
   result["BRAVO_APR_PERCENT_SHIFT_PER_HOUR"] = BRAVO_APR_PERCENT_SHIFT_PER_HOUR;
   result["BRAVO_APR_PERCENT_SHIFT_PER_ROUND"] = BRAVO_APR_PERCENT_SHIFT_PER_ROUND;
   result["BRAVO_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = BRAVO_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["BRAVO_BANDWIDTH_PRECISION"] = BRAVO_BANDWIDTH_PRECISION;
   result["BRAVO_BLOCKCHAIN_PRECISION"] = BRAVO_BLOCKCHAIN_PRECISION;
   result["BRAVO_BLOCKCHAIN_PRECISION_DIGITS"] = BRAVO_BLOCKCHAIN_PRECISION_DIGITS;
   result["BRAVO_BLOCKCHAIN_HARDFORK_VERSION"] = BRAVO_BLOCKCHAIN_HARDFORK_VERSION;
   result["BRAVO_BLOCKCHAIN_VERSION"] = BRAVO_BLOCKCHAIN_VERSION;
   result["BRAVO_BLOCK_INTERVAL"] = BRAVO_BLOCK_INTERVAL;
   result["BRAVO_BLOCKS_PER_DAY"] = BRAVO_BLOCKS_PER_DAY;
   result["BRAVO_BLOCKS_PER_HOUR"] = BRAVO_BLOCKS_PER_HOUR;
   result["BRAVO_BLOCKS_PER_YEAR"] = BRAVO_BLOCKS_PER_YEAR;
   result["BRAVO_CASHOUT_WINDOW_SECONDS"] = BRAVO_CASHOUT_WINDOW_SECONDS;
   result["BRAVO_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = BRAVO_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["BRAVO_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = BRAVO_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["BRAVO_CHAIN_ID"] = BRAVO_CHAIN_ID;
   result["BRAVO_COMMENT_REWARD_FUND_NAME"] = BRAVO_COMMENT_REWARD_FUND_NAME;
   result["BRAVO_CONTENT_APR_PERCENT"] = BRAVO_CONTENT_APR_PERCENT;
   result["BRAVO_CONTENT_CONSTANT_HF0"] = BRAVO_CONTENT_CONSTANT_HF0;
   result["BRAVO_CONTENT_REWARD_PERCENT"] = BRAVO_CONTENT_REWARD_PERCENT;
   result["BRAVO_CONVERSION_DELAY"] = BRAVO_CONVERSION_DELAY;
   result["BRAVO_CREATE_ACCOUNT_WITH_MODIFIER"] = BRAVO_CREATE_ACCOUNT_WITH_MODIFIER;
   result["BRAVO_NEW_ACCOUNT_CREATION_SHARE"] = BRAVO_NEW_ACCOUNT_CREATION_SHARE;
   result["BRAVO_CURATE_APR_PERCENT"] = BRAVO_CURATE_APR_PERCENT;
   result["BRAVO_EQUIHASH_K"] = BRAVO_EQUIHASH_K;
   result["BRAVO_EQUIHASH_N"] = BRAVO_EQUIHASH_N;
   result["BRAVO_FEED_HISTORY_WINDOW"] = BRAVO_FEED_HISTORY_WINDOW;
   result["BRAVO_GENESIS_TIME"] = BRAVO_GENESIS_TIME;
   result["BRAVO_HARDFORK_REQUIRED_WITNESSES"] = BRAVO_HARDFORK_REQUIRED_WITNESSES;
   result["BRAVO_INIT_MINER_NAME"] = BRAVO_INIT_MINER_NAME;
   result["BRAVO_INIT_PUBLIC_KEY_STR"] = BRAVO_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["BRAVO_INIT_PRIVATE_KEY"] = BRAVO_INIT_PRIVATE_KEY;
#endif
   result["BRAVO_INIT_SUPPLY"] = BRAVO_INIT_SUPPLY;
   result["BRAVO_INIT_TIME"] = BRAVO_INIT_TIME;
   result["BRAVO_IRREVERSIBLE_THRESHOLD"] = BRAVO_IRREVERSIBLE_THRESHOLD;
   result["BRAVO_LIQUIDITY_APR_PERCENT"] = BRAVO_LIQUIDITY_APR_PERCENT;
   result["BRAVO_LIQUIDITY_REWARD_BLOCKS"] = BRAVO_LIQUIDITY_REWARD_BLOCKS;
   result["BRAVO_LIQUIDITY_REWARD_PERIOD_SEC"] = BRAVO_LIQUIDITY_REWARD_PERIOD_SEC;
   result["BRAVO_LIQUIDITY_TIMEOUT_SEC"] = BRAVO_LIQUIDITY_TIMEOUT_SEC;
   result["BRAVO_MAX_ACCOUNT_NAME_LENGTH"] = BRAVO_MAX_ACCOUNT_NAME_LENGTH;
   result["BRAVO_MAX_ACCOUNT_WITNESS_VOTES"] = BRAVO_MAX_ACCOUNT_WITNESS_VOTES;
   result["BRAVO_MAX_ASSET_WHITELIST_AUTHORITIES"] = BRAVO_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["BRAVO_MAX_AUTHORITY_MEMBERSHIP"] = BRAVO_MAX_AUTHORITY_MEMBERSHIP;
   result["BRAVO_MAX_BLOCK_SIZE"] = BRAVO_MAX_BLOCK_SIZE;
   result["BRAVO_MAX_CASHOUT_WINDOW_SECONDS"] = BRAVO_MAX_CASHOUT_WINDOW_SECONDS;
   result["BRAVO_MAX_COMMENT_DEPTH"] = BRAVO_MAX_COMMENT_DEPTH;
   result["BRAVO_MAX_INSTANCE_ID"] = BRAVO_MAX_INSTANCE_ID;
   result["BRAVO_MAX_MEMO_SIZE"] = BRAVO_MAX_MEMO_SIZE;
   result["BRAVO_MAX_WITNESSES"] = BRAVO_MAX_WITNESSES;
   result["BRAVO_MAX_MINER_WITNESSES_HF0"] = BRAVO_MAX_MINER_WITNESSES_HF0;
   result["BRAVO_MAX_MINER_WITNESSES_HF17"] = BRAVO_MAX_MINER_WITNESSES_HF17;
   result["BRAVO_MAX_PERMLINK_LENGTH"] = BRAVO_MAX_PERMLINK_LENGTH;
   result["BRAVO_MAX_PROXY_RECURSION_DEPTH"] = BRAVO_MAX_PROXY_RECURSION_DEPTH;
   result["BRAVO_MAX_RESERVE_RATIO"] = BRAVO_MAX_RESERVE_RATIO;
   result["BRAVO_MAX_RUNNER_WITNESSES_HF0"] = BRAVO_MAX_RUNNER_WITNESSES_HF0;
   result["BRAVO_MAX_RUNNER_WITNESSES_HF17"] = BRAVO_MAX_RUNNER_WITNESSES_HF17;
   result["BRAVO_MAX_SHARE_SUPPLY"] = BRAVO_MAX_SHARE_SUPPLY;
   result["BRAVO_MAX_SIG_CHECK_DEPTH"] = BRAVO_MAX_SIG_CHECK_DEPTH;
   result["BRAVO_MAX_TIME_UNTIL_EXPIRATION"] = BRAVO_MAX_TIME_UNTIL_EXPIRATION;
   result["BRAVO_MAX_TRANSACTION_SIZE"] = BRAVO_MAX_TRANSACTION_SIZE;
   result["BRAVO_MAX_UNDO_HISTORY"] = BRAVO_MAX_UNDO_HISTORY;
   result["BRAVO_MAX_URL_LENGTH"] = BRAVO_MAX_URL_LENGTH;
   result["BRAVO_MAX_VOTE_CHANGES"] = BRAVO_MAX_VOTE_CHANGES;
   result["BRAVO_MAX_VOTED_WITNESSES_HF0"] = BRAVO_MAX_VOTED_WITNESSES_HF0;
   result["BRAVO_MAX_VOTED_WITNESSES_HF17"] = BRAVO_MAX_VOTED_WITNESSES_HF17;
   result["BRAVO_MAX_WITHDRAW_ROUTES"] = BRAVO_MAX_WITHDRAW_ROUTES;
   result["BRAVO_MAX_WITNESS_URL_LENGTH"] = BRAVO_MAX_WITNESS_URL_LENGTH;
   result["BRAVO_MIN_ACCOUNT_CREATION_FEE"] = BRAVO_MIN_ACCOUNT_CREATION_FEE;
   result["BRAVO_MIN_ACCOUNT_NAME_LENGTH"] = BRAVO_MIN_ACCOUNT_NAME_LENGTH;
   result["BRAVO_MIN_BLOCK_SIZE_LIMIT"] = BRAVO_MIN_BLOCK_SIZE_LIMIT;
   result["BRAVO_MIN_CONTENT_REWARD"] = BRAVO_MIN_CONTENT_REWARD;
   result["BRAVO_MIN_CURATE_REWARD"] = BRAVO_MIN_CURATE_REWARD;
   result["BRAVO_MIN_PERMLINK_LENGTH"] = BRAVO_MIN_PERMLINK_LENGTH;
   result["BRAVO_MIN_REPLY_INTERVAL"] = BRAVO_MIN_REPLY_INTERVAL;
   result["BRAVO_MIN_ROOT_COMMENT_INTERVAL"] = BRAVO_MIN_ROOT_COMMENT_INTERVAL;
   result["BRAVO_MIN_VOTE_INTERVAL_SEC"] = BRAVO_MIN_VOTE_INTERVAL_SEC;
   result["BRAVO_MINER_ACCOUNT"] = BRAVO_MINER_ACCOUNT;
   result["BRAVO_MIN_FEEDS"] = BRAVO_MIN_FEEDS;
   result["BRAVO_MINING_REWARD"] = BRAVO_MINING_REWARD;
   result["BRAVO_MINING_TIME"] = BRAVO_MINING_TIME;
   result["BRAVO_MIN_LIQUIDITY_REWARD"] = BRAVO_MIN_LIQUIDITY_REWARD;
   result["BRAVO_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = BRAVO_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["BRAVO_MIN_POW_REWARD"] = BRAVO_MIN_POW_REWARD;
   result["BRAVO_MIN_PRODUCER_REWARD"] = BRAVO_MIN_PRODUCER_REWARD;
   result["BRAVO_MIN_TRANSACTION_EXPIRATION_LIMIT"] = BRAVO_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["BRAVO_MIN_TRANSACTION_SIZE_LIMIT"] = BRAVO_MIN_TRANSACTION_SIZE_LIMIT;
   result["BRAVO_MIN_UNDO_HISTORY"] = BRAVO_MIN_UNDO_HISTORY;
   result["BRAVO_NULL_ACCOUNT"] = BRAVO_NULL_ACCOUNT;
   result["BRAVO_NUM_INIT_MINERS"] = BRAVO_NUM_INIT_MINERS;
   result["BRAVO_ORIGINAL_MIN_ACCOUNT_CREATION_FEE"] = BRAVO_ORIGINAL_MIN_ACCOUNT_CREATION_FEE;
   result["BRAVO_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = BRAVO_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["BRAVO_OWNER_AUTH_RECOVERY_PERIOD"] = BRAVO_OWNER_AUTH_RECOVERY_PERIOD;
   result["BRAVO_OWNER_CHALLENGE_COOLDOWN"] = BRAVO_OWNER_CHALLENGE_COOLDOWN;
   result["BRAVO_OWNER_CHALLENGE_FEE"] = BRAVO_OWNER_CHALLENGE_FEE;
   result["BRAVO_OWNER_UPDATE_LIMIT"] = BRAVO_OWNER_UPDATE_LIMIT;
   result["BRAVO_POST_AVERAGE_WINDOW"] = BRAVO_POST_AVERAGE_WINDOW;
   result["BRAVO_POST_MAX_BANDWIDTH"] = BRAVO_POST_MAX_BANDWIDTH;
   result["BRAVO_POST_REWARD_FUND_NAME"] = BRAVO_POST_REWARD_FUND_NAME;
   result["BRAVO_POST_WEIGHT_CONSTANT"] = BRAVO_POST_WEIGHT_CONSTANT;
   result["BRAVO_POW_APR_PERCENT"] = BRAVO_POW_APR_PERCENT;
   result["BRAVO_PRODUCER_APR_PERCENT"] = BRAVO_PRODUCER_APR_PERCENT;
   result["BRAVO_PROXY_TO_SELF_ACCOUNT"] = BRAVO_PROXY_TO_SELF_ACCOUNT;
   result["BRAVO_SECONDS_PER_YEAR"] = BRAVO_SECONDS_PER_YEAR;
   result["BRAVO_RECENT_RSHARES_DECAY_RATE_HF19"] = BRAVO_RECENT_RSHARES_DECAY_RATE_HF19;
   result["BRAVO_RECENT_RSHARES_DECAY_RATE_HF17"] = BRAVO_RECENT_RSHARES_DECAY_RATE_HF17;
   result["BRAVO_REVERSE_AUCTION_WINDOW_SECONDS"] = BRAVO_REVERSE_AUCTION_WINDOW_SECONDS;
   result["BRAVO_ROOT_POST_PARENT"] = BRAVO_ROOT_POST_PARENT;
   result["BRAVO_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = BRAVO_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["BRAVO_SAVINGS_WITHDRAW_TIME"] = BRAVO_SAVINGS_WITHDRAW_TIME;
   result["BRAVO_SECOND_CASHOUT_WINDOW"] = BRAVO_SECOND_CASHOUT_WINDOW;
   result["BRAVO_SOFT_MAX_COMMENT_DEPTH"] = BRAVO_SOFT_MAX_COMMENT_DEPTH;
   result["BRAVO_START_MINER_VOTING_BLOCK"] = BRAVO_START_MINER_VOTING_BLOCK;
   result["BRAVO_START_VESTING_BLOCK"] = BRAVO_START_VESTING_BLOCK;
   result["BRAVO_SYMBOL_TXT"] = BRAVO_SYMBOL_TXT;
   result["BRAVO_TEMP_ACCOUNT"] = BRAVO_TEMP_ACCOUNT;
   result["BRAVO_UPVOTE_LOCKOUT_HF7"] = BRAVO_UPVOTE_LOCKOUT_HF7;
   result["BRAVO_UPVOTE_LOCKOUT_HF17"] = BRAVO_UPVOTE_LOCKOUT_HF17;
   result["BRAVO_MAX_CASHOUT_WINDOWS"] = BRAVO_MAX_CASHOUT_WINDOWS;
   result["BRAVO_VESTING_WITHDRAW_INTERVALS"] = BRAVO_VESTING_WITHDRAW_INTERVALS;
   result["BRAVO_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = BRAVO_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["BRAVO_VESTING_WITHDRAW_INTERVAL_SECONDS"] = BRAVO_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["BRAVO_VOTE_CHANGE_LOCKOUT_PERIOD"] = BRAVO_VOTE_CHANGE_LOCKOUT_PERIOD;
   result["BRAVO_VOTE_DUST_THRESHOLD"] = BRAVO_VOTE_DUST_THRESHOLD;
   result["BRAVO_VOTE_REGENERATION_SECONDS"] = BRAVO_VOTE_REGENERATION_SECONDS;
   result["BRAVO_SYMBOL"] = BRAVO_SYMBOL;
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH"] = VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH2"] = VIRTUAL_SCHEDULE_LAP_LENGTH2;
   result["BRAVO_500_USERS"] = BRAVO_500_USERS;
   result["BRAVO_5K_USERS"] = BRAVO_5K_USERS;
   result["BRAVO_50K_USERS"] = BRAVO_50K_USERS;
   result["BRAVO_REWARD_MULTIPLIER_AT_500"] = BRAVO_REWARD_MULTIPLIER_AT_500;
   result["BRAVO_REWARD_MULTIPLIER_AT_5K"] = BRAVO_REWARD_MULTIPLIER_AT_5K;
   result["BRAVO_REWARD_MULTIPLIER_AT_50K"] = BRAVO_REWARD_MULTIPLIER_AT_50K;
   return result;
}

} } // bravo::protocol
